################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zetcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zetcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.3.13
          command:
            - etcd
            - --data-dir=/etcd-data
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://0.0.0.0:2379
            - --name=node1
          livenessProbe:
            httpGet:
              path: /health
              port: 2379
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          ports:
            - containerPort: 2379
              name: etcd
          volumeMounts:
          - name: zetcd-persistent-storage
            mountPath: /etcd-data
        - name: zetcd
          image: quay.io/coreos/zetcd:v0.0.5
          command:
            - zetcd
            - --zkaddr=0.0.0.0:2181
            - --endpoints=localhost:2379
          ports:
            - containerPort: 2181
              name: zetcd
      volumes:
      - name: zetcd-persistent-storage
        persistentVolumeClaim:
          claimName: zetcd-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zetcd-pv-claim
  labels:
    app: zetcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zetcd
  labels:
    app: zetcd
spec:
  type: ClusterIP
  ports:
  - port: 2181
    protocol: TCP
    targetPort: zetcd
  selector:
    app: zetcd
